#################################### common config : ####################################
spring:
  application:
    name: helloworld
  datasource:
    druid:
      master:
        name: master
        url: jdbc:mysql://192.168.87.162:3306/biapp?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&serverTimezone=GMT%2B8
        username: root
        password: Source@521
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        timeBetweenEvictionRunsMillis: 2000
        testWhileIdle: true
        validationQuery: select 1
        initialSize: 20
        minIdle: 5
        maxActive: 20
        maxWait: 3000
        filter:
          stat:
            enabled: true
          wall:
            enabled: true
            throw-exception: false

# 应用服务web访问端口
server:
  port: 8082

